version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
  - package-ecosystem: npm
    directory: /.devcontainer/terminal-layout
    schedule:
      interval: weekly
    labels:
      - dependencies
